# This is a basic workflow to help you get started with Actions

name: CI

on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      if: ${{ github.event.label.name == 'bug' }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${{ github.event.label.name }}
